bool detected

float32 x_picture # x position of the object in the image
float32 y_picture # y position of the object in the image

float32 x_global # x position of the object in the NED
float32 y_global # y position of the object in the NED
float32 z_global # z position of the object in the NED
float32 yaw # yaw position of the object in the NED

builtin_interfaces/Time last_detection_timestamp   # when the last detection of an aruco object happened, 

# float32 x_global_end # x position of the object in the image
# float32 y_global_end # end point

# float32 x_global_start # x position of the object in the real world
# float32 y_global_start # 

